//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AccountantProjectEntities : DbContext
    {
        public AccountantProjectEntities()
            : base("name=AccountantProjectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<gelirGiderTablosu> gelirGiderTablosu { get; set; }
        public virtual DbSet<OdemeTablosu> OdemeTablosu { get; set; }
        public virtual DbSet<stokTablosu> stokTablosu { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
