//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OdemeTablosu
    {
        public int OdemeID { get; set; }
        public string OdemeAdi { get; set; }
        public string OdemeTarihi { get; set; }
        public Nullable<int> userid { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
