//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stokTablosu
    {
        public int stokID { get; set; }
        public string UrunAdi { get; set; }
        public Nullable<int> StokAdedi { get; set; }
        public Nullable<int> userid { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
